# Generated by Django 4.2.8 on 2026-02-28 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("reasoning", models.TextField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CONSERVATIVE", "Conservative (Stablecoin Arbitrage)"),
                            ("MODERATE", "Moderate (Funding Rate Delta-Neutral)"),
                            ("AGGRESSIVE", "Aggressive (Cross-Chain Yield Rotation)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_address", models.CharField(max_length=42, unique=True)),
                (
                    "total_deposited",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("risk_tolerance", models.IntegerField(default=50)),
                (
                    "active_strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.strategy",
                    ),
                ),
            ],
        ),
    ]
