# Generated by Django 4.2.8 on 2026-02-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiactivitylog_strategy_userportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('STOP', 'STOP'), ('LIMIT', 'LIMIT')], max_length=10)),
                ('executed_action', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('STOP', 'STOP'), ('LIMIT', 'LIMIT')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('executed_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('amount', models.DecimalField(decimal_places=8, default=1.0, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('gas_fee', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('chain', models.CharField(default='BNB Chain', max_length=50)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Confirmed', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='signal',
            name='action',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('STOP', 'STOP'), ('LIMIT', 'LIMIT')], max_length=10),
        ),
    ]
