# Generated by Django 4.2.8 on 2026-02-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tradeexecution_alter_signal_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeexecution",
            name="wallet_address",
            field=models.CharField(blank=True, default="", max_length=42),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("Confirmed", "Confirmed"),
                    ("Pending", "Pending"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Confirmed",
                max_length=20,
            ),
        ),
    ]
