# Generated by Django 4.2.8 on 2026-02-28 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_tradeexecution_wallet_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exchange_name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(db_index=True, max_length=255)),
                ("strategy_type", models.CharField(max_length=100)),
                ("entry_price", models.FloatField()),
                ("exit_price", models.FloatField(null=True)),
                ("size", models.FloatField()),
                ("pnl", models.FloatField(default=0)),
                ("fees", models.FloatField(default=0)),
                ("tx_hash", models.CharField(max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="YieldSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol_name", models.CharField(max_length=255)),
                ("chain", models.CharField(max_length=50)),
                ("apy", models.FloatField()),
                ("risk_score", models.FloatField()),
                ("tvl", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userportfolio",
            name="active_strategy",
        ),
        migrations.RemoveField(
            model_name="userportfolio",
            name="pnl",
        ),
        migrations.RemoveField(
            model_name="userportfolio",
            name="user_address",
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="equity",
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="hedge_exposure",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="leverage",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="max_drawdown",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="net_delta",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="sharpe_ratio",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="spot_exposure",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="wallet_address",
            field=models.CharField(
                db_index=True, default="0x0", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="executed_action",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="executed_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="gas_fee",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="signal",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="tx_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tradeexecution",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userportfolio",
            name="current_balance",
            field=models.FloatField(default=10000.0),
        ),
        migrations.AlterField(
            model_name="userportfolio",
            name="total_deposited",
            field=models.FloatField(default=10000.0),
        ),
        migrations.CreateModel(
            name="YieldAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(db_index=True, max_length=255)),
                ("allocated_amount", models.FloatField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.yieldsource",
                    ),
                ),
            ],
        ),
    ]
