# Generated by Django 4.2.8 on 2026-02-28 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_exchangeprice_tradelog_yieldsource_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.DeleteModel(
            name="Signal",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="active_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.strategy",
            ),
        ),
    ]
